# Generated by Django 3.2.12 on 2023-01-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230113_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAllergy',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('food_allergy_name', models.CharField(max_length=255)),
                ('food_allergy_description', models.TextField()),
            ],
            options={
                'db_table': 'food_allergy',
            },
        ),
        migrations.CreateModel(
            name='Spices',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('spice_name', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
                ('upc_code', models.CharField(max_length=255)),
                ('size_quantity', models.FloatField()),
                ('size_metric', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'spices',
            },
        ),
    ]
