# Generated by Django 3.2.12 on 2023-01-20 07:00


from django.db import migrations


class Migration(migrations.Migration):
    def initiateData(self, schema_editor):

        from django.conf import settings
        from sqlalchemy import create_engine
        import pandas as pd
        from app.models import Spices, FoodAllergy
        xls1 = pd.ExcelFile('app/data/Spices.xlsx')
        xls2 = pd.ExcelFile('app/data/Common Food Allergies.xlsx')
        df1 = pd.read_excel(xls1, 'Sheet1')
        df2 = pd.read_excel(xls2, 'Allergies')

        for df1 in df1.itertuples():
            obj1 = Spices.objects.create(id=df1.ID, spice_name=df1.Name, ingredients=df1.Ingredients,
                                         upc_code=df1.UPC_Code, size_quantity=df1.Size_Quantity,
                                         size_metric=df1.Size_Metric)
            obj1.save()

        for df2 in df2.itertuples():
            obj1 = FoodAllergy.objects.create(id=df2.ID, food_allergy_name=df2.Allergy,
                                              food_allergy_description=df2.Description)
            obj1.save()

    dependencies = [
        ('app', '0005_foodallergy_spices'),
    ]

    operations = [migrations.RunPython(initiateData)
                  ]
