# Generated by Django 4.1.5 on 2023-01-23 10:55

from django.db import migrations


class Migration(migrations.Migration):
    def initiateData(self, schema_editor):

        import pandas as pd
        from app.models import SunshineAvailability, Zones, Spices, FoodAllergy
        xls = pd.ExcelFile('app/data/Vitamin D.xlsx')
        xls1 = pd.ExcelFile('app/data/Spices.xlsx')
        xls2 = pd.ExcelFile('app/data/Common Food Allergies .xlsx')

        df1 = pd.read_excel(xls, 'Vitamin D Strength')
        df2 = pd.read_excel(xls, 'Zones')

        df3 = pd.read_excel(xls1, 'Sheet1')
        df4 = pd.read_excel(xls2, 'Allergies')
        df3 = df3.astype(object).where(df3.notna(), None)
        df4 = df4.astype(object).where(df4.notna(), None)

        for df2 in df2.itertuples():
            obj1 = Zones.objects.create(id=df2.ZoneID, LatitudeMin=df2.LatitudeMin, LatitudeMax=df2.LatitudeMax,
                                        NorthSouth=df2.NorthSouth)
            obj1.save()

        for df1 in df1.itertuples():
            zones = Zones.objects.get(id=df1.ZoneID)
            obj = SunshineAvailability(ZoneID=zones, Month=df1.Month, Strength=df1.Strength)
            obj.save()

        for df3 in df3.itertuples():
            obj1 = Spices.objects.create(id=df3.ID, Name=df3.Name, Ingredients=df3.Ingredients,
                                         UPC_Code=df3.UPC_Code, Size_Quantity=df3.Size_Quantity,
                                         Size_Metric=df3.Size_Metric, Image_URL=df3.Image_URL,
                                         Recipes_URL=df3.Recipes_URL)
            obj1.save()

        for df4 in df4.itertuples():
            obj1 = FoodAllergy.objects.create(id=df4.ID, Allergy=df4.Allergy,
                                              Description=df4.Description)
            obj1.save()

    dependencies = [
        ('app', '0003_auto_20230123_1055'),
    ]

    operations = [
        migrations.RunPython(initiateData)
    ]
