# Generated by Django 4.1.5 on 2023-01-30 10:07

from django.db import migrations


class Migration(migrations.Migration):
    def initiateData(self, schema_editor):
        import pandas as pd
        from app.models import Nutrients
        xls = pd.ExcelFile('app/data/Nutrients .xlsx')

        df1 = pd.read_excel(xls, 'Nutrients')
        df1 = df1.astype(object).where(df1.notna(), None)

        for df1 in df1.itertuples():
            obj1 = Nutrients.objects.create(id=df1.ID, Nutrient=df1.Nutrient, Parent=df1.Parent,
                                            Supplements_Name=df1.Supplements_Name,
                                            Food_Nutrition_Name=df1.Food_Nutrition_Name,
                                            Active=df1.Active)
            obj1.save()
    dependencies = [
        ('app', '0004_auto_20230130_1007'),
    ]

    operations = [
        migrations.RunPython(initiateData)
    ]
