# Generated by Django 4.1.5 on 2023-01-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230130_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spices',
            name='Image_URL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='spices',
            name='Recipes_URL',
            field=models.URLField(null=True),
        ),
    ]
